image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/cache/pip"
  - conda env create -f environment.yml
  - source activate koopa

stages:
  - backend_testing

backend:
  stage: backend_testing
  script:
  - python --version
  - python backend/DB_Load/testDBloader.py