image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/cache/pip"
  - conda create --name test_env --file backend/DB_Load/requirements.txt
  - source activate test_env

stages:
  - backend_testing

backend:
  stage: backend_testing
  script:
  - python --version
  - python backend/DB_Load/testDBloader.py