image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/cache/pip"
  - conda create --name backend_test_env --file backend/DB_Load/requirements.txt
  - source activate backend_test_env

stages:
  - backend_testing
  - acceptance_testing

backend:
  stage: backend_testing
  script:
  - python --version
  - python backend/DB_Load/testDBloader.py

frontend:
  stage: acceptance_testing
  script:
    - conda install npm
    - conda --version
    - npm install chromedriver
    - python frontend/gui_test/guitest.py