image: "python:3.7"

before_script:
  - python --version

stages:
  - backend_testing

backend:
  stage: backend_testing
  script:
  - pip install -r backend/DB_Load/requirements.txt
  - python backend/DB_Load/testDBloader.py